version: "3.8"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - ./docker/data/kafka:/bitnami/kafka
      - ./docker/data/jmx-exporter:/opt/jmx-exporter
    networks:
      - kafka
    healthcheck:
      test: "kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1"
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 10s
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_METRICS_KAFKA_ENABLED=true
      - KAFKA_HEAP_OPTS=-Xms256m -Xmx512m

  kafka-exporter:
    image: docker.io/bitnami/kafka-exporter:1.7.0
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka
    command:
      - '--kafka.server=kafka:9092'
    healthcheck:
      test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9308; exit $$?;"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "9033:8080"
#    volumes:
#      - ./docker/config/kafka-ui-config.yml:/etc/kafkaui/dynamic_config.yaml
#    environment:
#      DYNAMIC_CONFIG_ENABLED: 'true'
#    networks:
#      - kafka
#    depends_on:
#      - kafka

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./docker/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - kafka

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

networks:
  kafka:
    driver: bridge

volumes:
  grafana-storage: {}
