global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'Payment Service Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'Payment Service'

  - job_name: 'Order Service Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Order Service'

  - job_name: 'Inventory Service Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Inventory Service'

  - job_name: 'Order Orchestrator Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'Order Orchestrator'

  - job_name: 'Kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9308']
        labels:
          application: 'Kafka'
