server:
  port: 8083

spring:
  application:
    name: order-orchestrator

---
spring:
  cloud.stream:
    function:
      definition: processor
    bindings:
      processor-in-0:
        destination: order-created
        group: order-orchestrator
      processor-out-0:
        destination: order-updated
        group: order-orchestrator
    kafka:
      binder:
        brokers: localhost
        defaultBrokerPort: 9094
        replication-factor: 1
---
service:
  endpoints:
    inventory: http://localhost:8081
    payment: http://localhost:8082