server:
  port: 8082

spring:
  application:
    name: payment-service
  webflux:
    base-path: /payment
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  tracing.sampling.probability: 1.0