spring:
  cloud.stream.kafka.binder:
    brokers: https://smiling-sunbeam-13908-eu2-kafka.upstash.io:9092
  r2dbc:
    url: r2dbc:postgresql://topsy.db.elephantsql.com/yxonzvcp
    username: yxonzvcp
    password: p1XcfkguHElKvicSJQZxGAcucSWqPGKZ

kafka:
  username: c21pbGluZy1zdW5iZWFtLTEzOTA4JJereriyCNLjpEaceB-dZfZPqXOo8aIv-TU
  password: YTA5N2RkMTUtMDQ4MS00OTdhLWJmMTItN2Q5OGI3YzZkYWU5
