server:
  port: 8081
  servlet:
    context-path: /inventory

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:15432/inventory
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: none
