# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push payment-service
        uses: docker/build-push-action@v5
        with:
          context: ./payment-service/
          file: ./payment-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saga-payment:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push inventory-service
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-service/
          file: ./inventory-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saga-inventory:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./order-service/
          file: ./order-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saga-order:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push order-orchestrator
        uses: docker/build-push-action@v5
        with:
          context: ./order-orchestrator/
          file: ./order-orchestrator/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saga-orchestrator:latest
          labels: ${{ steps.meta.outputs.labels }}